set -g default-terminal "xterm-256color"

set -g base-index 1

# Set the status bar background color to blue
set-option -g status-style bg=default

# Set the status bar foreground color to white (for better contrast)
set-option -g status-fg cyan

# Set the active pane border color to blue
set-option -g pane-active-border-style fg=blue

# synchronize all panes in a window
# don't use control S, too easily confused
# with navigation key sequences in tmux (show sessions)
bind C-A set-window-option synchronize-pane
